# This pipeline is for PRs only
trigger: none

resources:
  containers:
    - container: vscode-x64
      image: vscodehub.azurecr.io/vscode-linux-build-agent:bionic-x64
      endpoint: VSCodeHub
      options: --user 0:0

stages:
  - stage: Compile
    jobs:
      - job: Compile
        pool:
          vmImage: "Ubuntu-18.04"
        container: vscode-x64
        variables:
          VSCODE_ARCH: x64
        steps:
          - template: product-compile.yml
      - job: Hygiene
        pool:
          vmImage: "Ubuntu-18.04"
        container: vscode-x64
        variables:
          VSCODE_ARCH: x64
        steps:
          - template: product-hygiene.yml

  - stage: Windows
    dependsOn:
      - Compile
    pool:
      vmImage: VS2017-Win2016
    jobs:
      - job: Windows
        timeoutInMinutes: 90
        variables:
          VSCODE_ARCH: x64
        steps:
          - template: win32/product-build-win32.yml

  - stage: Linux
    dependsOn:
      - Compile
    pool:
      vmImage: "Ubuntu-18.04"
    jobs:
      - job: Linux
        container: vscode-x64
        variables:
          VSCODE_ARCH: x64
          NPM_ARCH: x64
        steps:
          - template: linux/product-build-linux.yml

  - stage: macOS
    dependsOn:
      - Compile
    pool:
      vmImage: macOS-latest
    jobs:
      - job: macOS
        timeoutInMinutes: 90
        variables:
          VSCODE_ARCH: x64
        steps:
          - template: darwin/product-build-darwin.yml
